boshinit/manifests/fixtures/manifest.yml, boshinit/manifests/job_properties.go, boshinit/manifests/job_properties_manifest_builder.go, boshinit/manifests/job_properties_manifest_builder_test.go
This turns on the Post Deploy Scripts feature - https://bosh.io/docs/post-deploy.html
Signed-off-by: Sameer Vohra <svohra@pivotal.io>
=> Sets enable_post_deploy flag in boshinit manifest

aws/cloudformation/templates/fixtures/cloudformation_with_cf_elb.json, aws/cloudformation/templates/fixtures/cloudformation_with_concourse_elb.json, aws/cloudformation/templates/fixtures/cloudformation_without_elb.json, aws/cloudformation/templates/nat_template_builder.go, aws/cloudformation/templates/nat_template_builder_test.go, bbl/fixtures/cloudformation-no-elb.json
We should be able to run a much smaller NAT instance than m4.large. Hopefully with this we can save a couple dollars on the ol' AWS bill.
=> Reduces size of NAT instance to t2.medium

boshinit/manifests/cloud_provider_manifest_builder.go, boshinit/manifests/cloud_provider_manifest_builder_test.go, boshinit/manifests/fixtures/manifest.yml, boshinit/manifests/job_properties.go, boshinit/manifests/job_properties_manifest_builder.go, boshinit/manifests/job_properties_manifest_builder_test.go, boshinit/manifests/jobs_manifest_builder.go, boshinit/manifests/jobs_manifest_builder_test.go, boshinit/manifests/manifest.go, boshinit/manifests/shared_properties_manifest_builder.go, boshinit/manifests/shared_properties_manifest_builder_test.go
Lots of the property values provided in the manifest are either not real properties in any job, or it's just providing the value that's already the default.
`./scripts/test` passed locally.
Integration tests also passed: https://mega.ci.cf-app.com/builds/238
=> boshinit/manifests: remove unnecessary manifest properties

cloudfoundry.md
Looks like following these instructions ends up setting up a websocket LB which forwards TCP 80 and 443 to the gorouter. Things like `cf logs` fail now without the router terminating TLS.
=> Removing disabling of router TLS termination

cloudconfig/gcp/cloud_config_generator.go, cloudconfig/gcp/cloud_config_template.go, cloudconfig/gcp/fixtures/cloud-config-cf-lb.yml, cloudconfig/gcp/fixtures/cloud-config-concourse-lb.yml, cloudconfig/gcp/fixtures/cloud-config-no-lb.yml
The GCP CPI supports a resource pool option named [`preemptible`][1]
that is useful to opt into for deployments with BOSH resurrector enabled.
[1]: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/f8918e185be638d84f85be0073572fdca3bd039b/src/bosh-google-cpi/README.md#bosh-resource-pool-options
=> Add vm_extension `preemptible` to cloud config

cloudconfig/gcp/cloud_config_template.go, cloudconfig/gcp/fixtures/cloud-config-cf-lb.yml, cloudconfig/gcp/fixtures/cloud-config-concourse-lb.yml, cloudconfig/gcp/fixtures/cloud-config-no-lb.yml
Although this machine type is already present under the names `default`
and `m3.medium`, it seems sensible to include it under its own name as
well, given that we've got vm_types `n1-standard-{2,4,8,16,32}`.
This is slightly related to PR #105, which addresses the documentation of this vm_type's non-existence.
=> Add vm_type `n1-standard-1` to cloud config

docs/cloudfoundry.md
Because bosh print-env isn't a thing
=> Change 'bosh print-env' to 'bbl print-env'

docs/concourse.md
The original documentation implied that `tls_bind_port` lived on the same level as `vm_type` or `vm_extensions`.
Also, removed extra horizontal rule
=> Clarify nesting of tls_bind_port

docs/concourse_aws.md
I have deployed Concourse to AWS using `bbl` and described the process in this guide.
=> Add doc describing Concourse on AWS deployment

README.md
Add some missing details to the GCP setup steps
- `gcloud iam service-accounts keys create` requires the full service account name
- `gcloud projects add-iam-policy-binding` requires a `serviceAccount:` prefix and the full service account name
=> Fix GCP commands in README.md

docs/concourse.md
* If `bind_port` is not defined, it defaults to port `8080`. Thus http
traffic is served on a non-standard port.
* This causes `http://concourse-url` to not work. Also `http` to `https`
redirection doesn't work.
* The load balancer is set-up to forward `443` and `80` to the backing web node.
Also ATC will redirect `80` to `443`. So this should still be nice and secure.
=> Instruct users to bind http traffic to port 80

README.md
ruby is required to render the bosh director's job templates
=> adds ruby as a dependency

docs/getting-started-aws.md
https://cloudfoundry.slack.com/archives/C2DBC3YGZ/p1502737611371791
Tested manually that this is sufficient, but can others verify that none of the steps that are now relegated to the H4 header are still necessary?
=> Promote `bbl print-env` workflow for AWS users

docs/concourse.md
Update the concourse release upload command to be generic (was specific to 2.5.1 version).
=> Make concourse release generic

helpers/env_id_manager.go, helpers/env_id_manager_test.go
- Regex didn't allow a valid two character name e.g. ci, but it did
allow a single character name and a three character name
Signed-off-by: Slawek Ligus <sligus@pivotal.io>
=> Fix name validation regex

bosh/manager.go, bosh/manager_test.go, commands/print_env.go, commands/print_env_test.go, terraform/aws/aws_templates.go, terraform/aws/fixtures/template_cf_lb.tf, terraform/aws/fixtures/template_cf_lb_with_domain.tf, terraform/aws/fixtures/template_concourse_lb.tf, terraform/aws/fixtures/template_no_lb.tf, terraform/gcp/fixtures/gcp_template_cf_lb.tf, terraform/gcp/fixtures/gcp_template_cf_lb_dns.tf, terraform/gcp/fixtures/gcp_template_concourse_lb.tf, terraform/gcp/fixtures/gcp_template_no_lb.tf, terraform/gcp/gcp_templates.go
Opens port 22 from the jumpbox to internal on AWS
Opens port 22 from the jumpbox to the director and the internal tag on GCP
Creates a new tag for the jumpbox, "env-id-jumpbox"
Renames the variable used for `bbl print-env` from BOSH_GW_PRIVATE_KEY to JUMPBOX_PRIVATE_KEY. I found this confusing, as BOSH_ALL_PROXY supercedes BOSH_GW_PRIVATE_KEY in all cases.
[#151273881]
RE: #197
=> Changes to enable `bosh ssh job/0`

scripts/bbl
```
unclephil:bosh-bootloader efarrar$ ./scripts/bbl version
++ git rev-parse --short=6 HEAD
+ go install '-ldflags=-X main.Version=92d424' github.com/cloudfoundry/bosh-bootloader/bbl
+ bbl version
bbl 887d43 (darwin/amd64)
unclephil:bosh-bootloader efarrar$ 
```
=> bbl version reports SHA in scripts/bbl

commands/print_env.go, commands/print_env_test.go
Setting `ServerAliveInterval` will keep the proxy tunnel from hanging up when connected to the typical ubuntu stemcell.  This is a temporary fix while waiting on bosh-cli to natively support tunneling.
=> Adds keepalive setting to ssh tunnel

README.md
- the cert doesn't parse correctly without the surrounding quotes
You get an annoying pem encoding error without the quotes when you actually try to use bosh.
=> use correct syntax for "$(bbl print-env)"

bosh/manager.go, bosh/manager_test.go
We currently assert that if you set the director IP to 10.2.0.6 then the director URI will be `https://10.0.0.6:25555`
=> Correlate director address to CIDR

docs/advanced.md
1.  Added -e and \n to update the tfvars file on a new line.
2.  I believe that the variable to be modified is meant to be vpc_cidr rather than cidr_block
Might be worth mentioning the smallest cidr block that can currently be used is \20.  Reasonable for cf.  Probably overkill for concourse.
=> Small language updates to cidr block update sect

Gopkg.lock, certs/validator.go, certs/validator_test.go, commands/interfaces.go, commands/lb_args_handler.go, commands/lb_args_handler_test.go, docs/getting-started-azure.md, fakes/certificate_validator.go, vendor/golang.org/x/crypto/pkcs12/bmp-string.go, vendor/golang.org/x/crypto/pkcs12/bmp-string_test.go, vendor/golang.org/x/crypto/pkcs12/crypto.go, vendor/golang.org/x/crypto/pkcs12/crypto_test.go, vendor/golang.org/x/crypto/pkcs12/errors.go, vendor/golang.org/x/crypto/pkcs12/internal/rc2/bench_test.go, vendor/golang.org/x/crypto/pkcs12/internal/rc2/rc2.go, vendor/golang.org/x/crypto/pkcs12/internal/rc2/rc2_test.go, vendor/golang.org/x/crypto/pkcs12/mac.go, vendor/golang.org/x/crypto/pkcs12/mac_test.go, vendor/golang.org/x/crypto/pkcs12/pbkdf.go, vendor/golang.org/x/crypto/pkcs12/pbkdf_test.go, vendor/golang.org/x/crypto/pkcs12/pkcs12.go, vendor/golang.org/x/crypto/pkcs12/pkcs12_test.go, vendor/golang.org/x/crypto/pkcs12/safebags.go
I had some difficulty using bbl to deploy a director for CloudFoundry on Microsoft Azure. The file containing the password for the load balancer certificate was terminated with a newline and so bbl was setting the password in the tfvars as `SuperSecretPassword\n`. When I ran `bbl up` the `terraform apply` step was failing as the password did not match.
I added functionality to strip any terminating newlines from the password file, and as golang supports validation of PKCS12/PFX certificates I also added a password check at the plan stage to ensure it is correct.
I've been torn between a couple of different solutions to this problem. I think the code in this PR is the simplest way to add the functionality required, but I'm not super keen on the validator struct in its current form. It …
=> Add validation of PKCS12 (Azure) cert passwords

plan-patches/README.md, plan-patches/iso-segs-gcp/cloud-config/routing-iso-segs.yml, plan-patches/iso-segs-gcp/terraform/routing-iso-segs.tf
the terraform is kind of a rough draft, but it totally works!
it is what we're using in our CI environments on the routing team.
we may PR some more changes later to better lock down all the things / improve UX for websockets, etc.
=> plan patch for routing isolation segments on GCP

plan-patches/bosh-lite-gcp/terraform/bosh-lite_override.tf
- default port range from cf-deployment
=> Firewall rule for TCP routing on GCP bosh-lite

README.md
`--cert` and `--key` are no longer the right flags.
=> Fix docs to say --lb-cert and --lb-key

README.md
fixed reference to Concourse website to the new `.org` domain
=> fixed reference to Concourse website

cloudconfig/azure/base_ops_template.go, cloudconfig/azure/fixtures/azure-ops.yml
Azure CPI doesn't support the cloud property `type: gp2` for the ephemeral disk.
See: https://bosh.io/docs/azure-cpi.html#resource-pools
=> Remove the unsupported cloud property "type: gp2"

docs/getting-started-gcp.md
`--lb-comdin` isn't a recognized flag. I assume it's meant to be `--lb-domain`
=> Fix typo: --lb-comdin -> --lb-domain

plan-patches/cfcr-gcp/README.md, plan-patches/cfcr-gcp/terraform/cfcr_iam_override.tf
Adds additional permissions required for GCP service accounts when applying CFCR GCP plan patches.
=> Service account permissions

terraform/azure/templates/cf_dns.tf, terraform/azure/templates/cf_lb.tf, terraform/azure/templates/concourse_lb.tf, terraform/azure/templates/network.tf, terraform/azure/templates/network_security_group.tf, terraform/azure/templates/output.tf, terraform/azure/templates/resource_group.tf, terraform/azure/templates/storage.tf
Reverts cloudfoundry/bosh-bootloader#309
This doesn't actually work because of a few problems:
- original PR didn't include a variable definition for `var.resource_group_name`
- intended PR contained `variable "resource_group_name" {default = "${var.env_id}-bosh"}` but this change didn't get pushed
- HCL doesn't let you interpolate variable defaults with other variables
- see [these](https://github.com/hashicorp/terraform/issues/14343) [issues](https://github.com/hashicorp/terraform/issues/4084) in Terraform
- injecting a reasonable default with `terraform/azure/input_generator.go` causes failures because the resource group `${envID}-bosh` doesn't actually exist yet
- this means we would have to adopt a strategy similar to the hosted DNS zone strategy for AWS, where we actually check if …
=> Revert "Azure resource group name is configurable"

docs/cf-lbs.md, docs/cloudfoundry.md, docs/concourse.md, docs/credhub.md, docs/getting-started-aws.md, docs/getting-started-azure.md, docs/getting-started-gcp.md, docs/getting-started-openstack.md, docs/getting-started-vsphere.md, docs/howto-target-bosh-director.md
Primarily extract instructions for targetting BOSH Director into its own doc, and link to it from all Getting Started docs.
=> docs: improve consistency

cloudconfig/azure/fixtures/azure-ops.yml, cloudconfig/azure/ops_generator.go
because it sometimes resolve dns very slow on Azure environemnt.
=> remove google dns for Azure IAAS

docs/credhub.md
This minimal PR makes a change to the credhub documentation section that describes the behavior of the credhub CLI when `CREDHUB_PROXY` is set. If `bbl print-env` has been `eval`ed before this statement as the docs suggest, then `CREDHUB_PROXY` should be set in the environment, and the `http_proxy` env var should not be necessary to communicate with the CredHub server.
=> Remove unnecessary http_proxy env var

plan-patches/cfcr-azure/ops/cloud-provider.yml, plan-patches/cfcr-azure/ops/use-latest-kubo-release.yml, plan-patches/cfcr-gcp/cfcr-ops.yml
* 0.24 will have breaking changes in property names
We plan to release 0.24 this week.
Additionally, I have removed ops-file that was no longer used.
=> Prepare properties for CFCR 0.24

plan-patches/cfcr-gcp/cfcr-ops.yml
Removed an extra key in the path according to https://github.com/cloudfoundry-incubator/kubo-deployment/blob/v0.24.0/manifests/ops-files/iaas/gcp/cloud-provider.yml
=> Update cfcr-ops for 0.24

plan-patches/cfcr-vsphere/README.md
For the upcoming v0.22.0 CFCR release, the following edits to the documentation are required:
* fix to missing backslash (also necessary for the current release!)
* Additional instruction to add vm-extension to cloud config
* Amendment to the deploy instruction to use vm-extension in cloud config
* Amendment to the deploy instruction to use runtime config bosh dns
* Amendment to the deploy instruction to remove an ops-file which added named vm_extension which does not exist for vsphere
=> Amends cfcr deployment instructions for v0.22.0

commands/commands_usage.go, commands/ssh.go, commands/ssh_test.go
For now, this only supports executing commands on the director, as it is useful for us on the MySQL team.
In summary, this allows you to execute a command a la how ssh would originally run.
Please let me know of any feedback you have.
=> Add `--cmd` for `bbl ssh` to execute commands

plan-patches/README.md, plan-patches/s3-blobstore-aws/README.md, plan-patches/s3-blobstore-aws/terraform/s3_blobstore_buckets.tf, plan-patches/s3-blobstore-aws/terraform/s3_blobstore_iam.tf, plan-patches/s3-blobstore-aws/terraform/s3_blobstore_outputs.tf
Hi,
This is a PR to add a plan-patch to create S3 and IAM resources for a CF deployment to use for an external blobstore. We're planning to use this in our CI to reduce cost and felt that it would be useful to others that still deploy to AWS.
Please let us know if you have any questions.
Thanks,
@paulcwarren and Dave
=> Add plan-patch for AWS S3 Blobstore Resources

terraform/gcp/template_generator.go, terraform/gcp/template_generator_test.go
We're getting the following error when trying to upgrade from bbl v6 to v7 when using CF lbs. After investigation noticed that deleting the instance group at the same time as removing the backend from the backend service causes an issue because the terraform google provider is trying to delete the instance group before removing the backend from the backend service.
Here's a snippet of the error we're seeing:
```
Error: Error applying plan:
1 error(s) occurred:
* google_compute_instance_group.router-lb-2 (destroy): 1 error(s) occurred:
* google_compute_instance_group.router-lb-2: Error deleting InstanceGroup: googleapi: Error 400: The instance_group resource 'projects/cf-release-integration-luna/zones/us-west1-c/instanceGroups/luna-fresh-router-lb-2-us-west1-c' is already being used by …
```
=> Fix zone list restriction

plan-patches/cfcr-gcp/terraform/cfcr_iam_override.tf
Replace changing policy to add iam membership.
Change policy deletes all the permissions when terraform upgrade fails
=> Set roles for account separately

plan-patches/n-cf-gcp/README.md, plan-patches/n-cf-gcp/cf-lb-ops.yml, plan-patches/n-cf-gcp/cloud-config/cf-lbs-ops-override.yml, plan-patches/n-cf-gcp/terraform/cf-dns_override.tf, plan-patches/n-cf-gcp/terraform/cf-lb_override.tf, plan-patches/n-cf-gcp/update-configs.sh
I've noticed that a few teams, including ours (Release Integration), use multiple environments on GCP and for each one of them they create a whole bbl environment which includes jumpbox and director for each.
Since most of these teams are testing their releases with CF context. Having one bbl environment with support for multiple CF deployments makes it easier to manage all these deployments.
This plan patch adds support for multiple CF load balancers and DNS entries which can each be used by its own CF deployment.
=> Plan patch for multiple CF gcp environments

docs/cf-lbs.md, plan-patches/bosh-lite-aws/terraform/bosh-lite_override.tf, terraform/aws/templates/cf_lb.tf, terraform/aws/templates/iso_segments.tf
- traffic on 4443 used to be necessary to circumvent a limitation
of AWS classic load balancers where wouldn't allow traffic on
443 for web sockets.
- bbl now uses Network Load Balancers which no longer needs traffic on 4443
plan-patches were not modified
=> Traffic on 4443 to gorouter is no longer required

bosh/all_proxy_getter.go, bosh/cli_provider.go, bosh/cli_provider_test.go, commands/print_env.go, commands/print_env_test.go, storage/jumpbox.go, storage/jumpbox_test.go
I'm writing a `bbl-adapter` for PCF deployments. The intent is to generate bbl state and use it as a drop-in replacement for `environment`-style resources in concourse, that cf-d tasks understand.
At present, bbl forces `jumpbox@` in `bbl print-env`. This change allows for a custom user in the Jumpbox URL.
=> Allow for non-default jumpbox user in bbl-state

plan-patches/README.md, plan-patches/openvpn-aws/cloud-config/openvpn_vip.yml, plan-patches/openvpn-aws/terraform/openvpn_override.tf
Hi,
This PR adds support for a BOSH deployed OpenVPN server on AWS. It adds a new public subnet with a security group to allow VPN traffic on TCP port 1194. It also adds a `vip` network to the cloud-config so that the openvpn server can have a public IP assigned. To keep things simple, we are only utilizing the first availability zone. We are open to supporting multiple AZs, but couldn't find a way to craft an ops-file to update the cloud-config based on the terraform outputs non-programatically.  See [this post](https://cloudfoundry.slack.com/archives/C0FA9UNAH/p1552513669015400).
[#164386432](https://www.pivotaltracker.com/story/show/164386432)
_Paul
cc @davewalter @julian-hj
=> Add a plan-patch to add support for an OpenVPN server

aws/client.go, cloudconfig/aws/ops_generator.go, cloudconfig/aws/ops_generator_test.go, terraform/aws/input_generator.go, terraform/aws/input_generator_test.go, terraform/aws/templates/base.tf
This reverts commit b91a39b73665f19d4ad9a29394746b8339388bc6.
This fixes an issue of version v8.0.0 where it was triggering a recreation of the `bosh_subnet` which will fail because the bosh director and jumpbox live in that subnet.
=> Revert "Exclude the 'd' availablity zone from aws"

renderers/factory.go, renderers/factory_test.go, renderers/shell_types.go, renderers/yaml.go, renderers/yaml_test.go
We (the CF-Toolsmiths team) are building automation around creating environments using bbl and cf-deployment. In order to provide to our users the metadata required to target their BOSH director and use their new environments, we need to programmatically parse the output of bbl print-env. Seems like the easiest way to do this was to add a YAML renderer (JSON would have been our first choice, but was more complicated due to having to add trailing commas, starting and ending braces, etc.). This will hopefully also make it easier for all users to programmatically interact with bbl.
cc @rowanjacobs @nhsieh
=> Add yaml renderer for bbl print-env

commands/commands_usage.go, commands/commands_usage_test.go
This PR adds YAML renderer shell type to `bbl print-env` help message.
YAML render support was added in https://github.com/cloudfoundry/bosh-bootloader/pull/487 PR.
=> Add missing yaml renderer shell type for print-env help message

commands/commands_usage.go, commands/commands_usage_test.go, commands/print_env.go, commands/print_env_test.go
In order to allow the new Toolsmiths pooled cf-deployment environments to work with cf-deployment-concourse-tasks, we would like to provide a metadata file, in the [format](https://pivotal.github.io/cf-toolsmiths-docs/pivotal-cf-experimental/toolsmiths-envs/cf-deployment/) that the Toolsmiths API provides, to `bbl` in lieu of a traditional bbl-state directory.
This change should not affect `bbl` usage at all for those who are using the traditional bbl-state workflow.
=> Print-env can take Toolsmiths metadata file

terraform/aws/templates/cf_lb.tf, terraform/aws/templates/concourse_lb.tf, terraform/aws/templates/iam.tf, terraform/aws/templates/iso_segments.tf, terraform/aws/templates/ssl_certificate.tf
Resolves https://github.com/genevieve/leftovers/issues/86
See CI: https://infra.ci.cf-app.com/teams/main/pipelines/bosh-bootloader/jobs/bbl-aws-concourse-bump-deployments/builds/122
=> Tag resources that use short_env_id so that leftovers can delete them.

plan-patches/cf-azure/ops/rename-network-and-deployment.yml, plan-patches/cf-azure/ops/scale-to-one-az.yml, plan-patches/cf-azure/ops/use-cf-resource-group.yml, plan-patches/cf-azure/ops/use-cf-subnet.yml
Since consul was deleted in cf-deployment v5.0.0, it was deleted from azure patches.
cf-deployment v5.0.0: https://github.com/cloudfoundry/cf-deployment/releases/tag/v5.0.0
=> Remove consul from cf-azure patches

plan-patches/bosh-lite-aws/create-director-override.sh, plan-patches/bosh-lite-aws/delete-director-override.sh
This change makes the `create-director-override.sh` script consistent with its GCP counterpart, and also prevents users of this ops-file from accidentally sharing secrets (debug log level will show vars-file/vars-store content, among other things.)
=> Don't set BOSH_LOG_LEVEL to debug in bosh-lite-aws override script

cloudconfig/vsphere/base_ops_template.go
Before this commit one was unable to use the 500GB_ephemeral_disk
extension on vsphere because it had no value for disk.
Signed-off-by: Arjun Sreedharan <asreedharan@pivotal.io>
cc @sophiewigmore
=> Add disk value for 500 GB ephemeral disk vm extension for vsphere

terraform/aws/templates/iam.tf
With the current IAM role BOSH will fail to lodge spot instance request since the provided credentials do not have permission to create the service-linked role.
```
Task 148298 | 08:46:25 | Updating instance nats: nats/ec00fc7f-556c-424b-812e-5eddbf5077d5 (0) (canary) (00:00:52)
L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'Spot instance creation failed: #<Bosh::Clouds::VMCreationFailed: Failed to get spot instance request: #<Aws::EC2::Errors::AuthFailureServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances.>>' in 'create_vm' CPI method (CPI request ID: 'cpi-457896')
```
When creating a Spot Request **AWSServiceRoleForEC2Spot** service-linked role needs to be created or exist …
=> Add iam:CreateServiceLinkedRole permission to iam role policy

plan-patches/network-lb-gcp/README.md
Clarify that you must run bbl plan with --lb-type cf and --lb-domain in
order for this plan patch to work.
Co-authored-by: David McClure <dmcclure@pivotal.io>
@rowanjacobs
=> Update README for network-lb-gcp plan-patch

terraform/aws/templates/base.tf, terraform/aws/templates/cf_dns.tf, terraform/aws/templates/cf_lb.tf, terraform/aws/templates/concourse_lb.tf, terraform/aws/templates/iam.tf, terraform/aws/templates/iso_segments.tf, terraform/aws/templates/lb_subnet.tf, terraform/aws/templates/vpc.tf
Hi! Looks like the latest BBL templates for AWS are also broken on v15 of terraform (similar to https://github.com/cloudfoundry/bosh-bootloader/issues/523). This PR updates those templates to be compatible. I have tested it out with a standard BBL up on AWS (install, NOT upgrade) and this now works with v8.4.41.
This PR can serve as a template for the fix, or for others who want to be unblocked and use the latest BBL for AWS.
---
- This adds a '=' to each "tags" block as required by aws provider
- This adds a "required_providers" block as recommended by terraform
deprecation warning
- This removes quotes from the types for variables as required by
terraform v15
- This removes quotes from arrays as recommended by terraform
deprecation warning
Signed-off-by: Neil Hickey <nhickey@vmware.com>
=> Update aws templates to be terraform v15 compliant

plan-patches/README.md, plan-patches/http2-lb-gcp/README.md, plan-patches/http2-lb-gcp/terraform/http2-cf-lb-gcp_override.tf
We are working on a feature to  add the ability for the gorouter to accept http2 requests. 
Corresponding issue: https://github.com/cloudfoundry/routing-release/issues/200
To fully support end-to-end http2 traffic, load balances must be able to accept http2 requests. This is a plan patch to make sure the load balancer in front CF can accept http2 traffic.
Right now this patch is not compatible with the current gorouter because it blocks h2 requests. We will update the README.md with the version of cf-deployment/routing-release it will work with once we are done with the feature.
=> add plan-patch to enable HTTP2 in GCP load balancer

cloudconfig/azure/fixtures/azure-ops.yml
We use 3 VM sizes, probably poorly named: 
* minimal (can run in 1-2GB of memory and shared core)
* small (needs 4-8GB of memory and at least 1 real core)
* small-highmem (needs 12+ GB of memory and at least 1 real core)
This change updates those 3 VM types to use 4th generation hardware and the cheapest option for each requirement.
=> Update Azure VM sizes used in CF-D to be cheaper

terraform/openstack/templates/provider.tf
terraform-provider-openstack release 1.44 updates major version of terraform-plugin-sdk from `v1` to `v2` https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/CHANGELOG.md#1440-2-october-2021
It causes BBL error: `provider.openstack: Incompatible API version with plugin. Plugin version: 5, Core version: 4`
=> Openstack Incompatible API Fix

cloudconfig/aws/base_ops_template.go, cloudconfig/aws/fixtures/aws-ops.yml, cloudconfig/azure/base_ops_template.go, cloudconfig/azure/fixtures/azure-ops.yml, cloudconfig/gcp/base_ops_template.go, cloudconfig/gcp/fixtures/gcp-ops.yml
I did incorrectly ported over the community RFC 0009 intensions around compilation VM sizes, forgetting that they have to refer to VM Type in BOSH. So I added a lot of named VM types for modern VM sizes as well, allowing you to change compilation (or other VM) sizes more flexibly later.
=> Fix compilation vms not found with modern VM sizes

cloudconfig/aws/base_ops_template.go, cloudconfig/aws/fixtures/aws-ops.yml, cloudconfig/azure/base_ops_template.go, cloudconfig/azure/fixtures/azure-ops.yml, cloudconfig/gcp/base_ops_template.go, cloudconfig/gcp/fixtures/gcp-ops.yml
* Small highmem may not be enough for diego with CATS in high
parallelism, so we want to offer some additional cross-iaas
standardized options. Medium & large would be balanced CPU/memory,
whereas medium-highmem would be a larger memory-rich cell
Signed-off-by: David Stevenson <stevensonda@vmware.com>
=> Standardized medium and large VM sizes, add medium-highmem option

README.md, docs/cleaning-up.md
- `bbl destroy` is the replacement for `bbl down`, and `destroy` is the preferred command, though `bbl down` still exists as an undocumented (in `bbl -h`) command for backward compatibility purpose.
- Hence, this commit replaces references to `bbl down` with `bbl destroy` in docs.
(see discussion: https://github.com/cloudfoundry/bosh-bootloader/issues/542)
=> Fix docs: reference `bbl destroy` instead of `bbl down`

ci/dockerfiles/deployment/Dockerfile, ci/pipelines/bosh-bootloader.yml, ci/tasks/bump-deployments/task.yml, ci/tasks/download-terraform/task.yml
- changed tasks to our general maintained docker images
- temp remove the creation of new crygenic-bbl docker-images to see if we actually need them
- refelect the credentials names as we use them in the infra credhub
these changes are all needed for the move to bosh.ci.cloudfoundry.org
=> update ci for the main branch

acceptance-tests/bbl/init_test.go, acceptance-tests/bbl/print_env_test.go, acceptance-tests/bbl/upgrade_test.go
this pr wil fix the acceptance test.
for now it disables the upgrade scenario.
as there is not easy upgrade scenario from bbl 8.4 which contains terrafrom 0.12.
to the new terrafrom 1.3.9
the bucket change is due to the fact that we do not have access to that bucket anymore.
and so i created a new bucket in the foundation gcp account
=> make the acceptance tests work again.

terraform/aws/templates/cf_lb.tf
* we need a longer idle timeout than the default 60s for some tests
=> Variable to make AWS ELB idle timeout configurable

plan-patches/byoresource-group-azure/terraform/resource_group_override.tf, plan-patches/cf-azure/terraform/cf_lb_override.tf, plan-patches/cf-azure/terraform/cf_resource_group_override.tf, plan-patches/cf-azure/terraform/cf_subnet.tf, plan-patches/cf-lite-azure/terraform/cf_lb_override.tf, plan-patches/cf-lite-azure/terraform/cf_subnet.tf, plan-patches/cfcr-azure/terraform/cfcr_lb_override.tf, plan-patches/cfcr-azure/terraform/cfcr_subnet.tf, terraform/azure/templates/cf_dns.tf, terraform/azure/templates/cf_lb.tf, terraform/azure/templates/concourse_lb.tf, terraform/azure/templates/network.tf, terraform/azure/templates/network_security_group.tf, terraform/azure/templates/resource_group.tf, terraform/azure/templates/storage.tf, terraform/azure/templates/vars.tf
Newer version of terraform introduced changes to the template syntax.
This PR fixes all Azure templates so that:
```
bbl up
bbl plan --lb-type concourse && bbl up
bbl plan --lb-type cf ....  && bbl up
```
all execute without errors.
=> Fix azure templates according to the newer terraform versions

ci/pipelines/bosh-bootloader.yml
The cf-deployment-concourse-tasks/bosh-deploy/task.yml task expects that the OPS_FILES variable is formatted as a list of space-separated file names.
See: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/03f785df60c5d851ee47aee4967b06fa7327d8e2/shared-functions#L122-L125
Configuring it as a YAML array of file names led to the following error when it tries to build up the `-o` options for bosh:
```
invalid argument for flag `-o, --ops-file' (expected []opts.OpsFileArg):
Reading ops file
'ops-files/["operations/use-compiled-releases.yml","operations/experimental/fast-deploy-with-downtime-and-danger.yml"]':
Opening file
ops-files/["operations/use-compiled-releases.yml","operations/experimental/fast-deploy-with-downtime-and-danger.yml"]:
open …
```
=> ci: Fix ops files for deploy-cf task

terraform/openstack/templates/resources.tf
https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_subnet_v2#allocation_pools
```
bbl latest-error
╷
│ Error: Unsupported argument
│
│   on bbl-template.tf line 178, in resource "openstack_networking_subnet_v2" "bosh_subnet":
│  178:   allocation_pools = {
│
│ An argument named "allocation_pools" is not expected here. Did you mean to
│ define a block of type "allocation_pools"?
```
=> Update resources.tf - allocation_pool as a block

terraform/openstack/templates/resources-outputs.tf, terraform/openstack/templates/resources-vars.tf, terraform/openstack/templates/resources.tf
The change, thanks to the new variables, allows easy network configuration of: 
- `subnet_cidr` CIDR representing IP range for this subnet, IPv4, default = "10.0.1.0/24"
- `subnet_allocation_pool_start` - The start IP address available for use with DHCP in this subnet, each IP range must be from the same CIDR that the subnet is part of, default = "10.0.1.200"
- `subnet_allocation_pool_end` - The end IP address available for use with DHCP in this subnet, each IP range must be from the same CIDR that the subnet is part of, default = "10.0.1.254"
- `subnet_gateway_ip` - Default gateway used by devices in this subnet, default = "10.0.1.1"
These variables have default values set to those that were in the previous configuration, therefore without overwriting these variables, the configuration …
=> OpenStack terraform subnet customization

terraform/gcp/templates/bosh_director.tf, terraform/gcp/templates/cf_lb.tf
* currently we have to use external IPs for all VMs to enable outgoing traffic (`ephemeral_external_ip: true` in BOSH cloud-config)
* to avoid allocating a large number of external IPs (and possibly leaving behind cost-incurring orphans), we should use a NAT gateway instead as on other infrastructures
* this basic NAT configuration is taken from the Terraform manual: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_router_nat#example-usage---router-nat-basic
=> Enable NAT Gateway for GCP

cloudconfig/gcp/fixtures/gcp-ops.yml, cloudconfig/gcp/ops_generator.go
* since v9.0.11 bbl deploys a cloud NAT gateway on GCP for outgoing traffic, so we don't need external IPs anymore
* main problem were orphaned external IPs which incur additional cost
=> Disable ephemeral_external_ip for GCP cloud config

terraform/gcp/templates/bosh_director.tf
* with static port allocation we have a performance degradation
=> Enable dynamic port allocation for GCP Cloud NAT gateway

terraform/cloudstack/templates/provider.tf
For Cloudstack only, the required providers are genereted to the `bbl-template.tf` file. Therefore it is not possible to override the provider versions.
This change removes the required providers definition from the `bbl-template.tf` file for Cloudstack so the provider versions can be overridden like the others IaaS.
=> Removing required providers for cloudstack

storage/fixtures/upped/bosh-deployment/ci/bosh-alpha-compiled-releases/configure.sh, storage/fixtures/upped/bosh-deployment/ci/compiled-releases/configure.sh
Trying to remove all outdated lastpass references since we use credhub creds generally now.
=> Remove outdated lastpass references from test fixtures

aws/client.go, bosh/executor.go, bosh/executor_test.go, bosh/manager.go, bosh/manager_test.go, config/downloader.go, config/global_flags.go, config/load_state_test.go, config/merger.go, fakes/bosh_executor.go, storage/aws.go, terraform/aws/input_generator.go, terraform/aws/input_generator_test.go, terraform/aws/templates/base.tf
I am looking to use AWS Assume Role with `bbl`. I see there has been some work done in the past to add this support in (see the [aws-assume-role-support](https://github.com/cloudfoundry/bosh-bootloader/tree/aws-assume-role-support) branch), however it looks like that work never got merged into `main`.
I tried it out myself by rebasing that branch on top of `main` and building a local copy to see if it would work. I was able to successfully `bbl up` a director using the `BBL_AWS_ASSUME_ROLE` env var so thought I'd open this PR to get that work merged in.
cc @danielfor and @ystros who originally contributed the commits to the [aws-assume-role-support](https://github.com/cloudfoundry/bosh-bootloader/tree/aws-assume-role-support) branch.
=> AWS assume role

terraform/azure/templates/cf_lb.tf
fix #595
When changing Application Gateway to Standard_v2, priority must be added to request_routing_rule.
[for more info..](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#priority)
and Standard_v2 SKU supports standard SKU public IPs that are static only.
[for more info..](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/configure-public-ip-application-gateway)
=> Fix azure application gateway sku

plan-patches/s3-blobstore-aws/terraform/s3_blobstore_outputs.tf
The new names harmonize better with the cf-deployment ops files:
- https://github.com/cloudfoundry/cf-deployment/blob/main/operations/use-external-blobstore.yml
- https://github.com/cloudfoundry/cf-deployment/blob/main/operations/use-s3-blobstore.yml
Note that this is a breaking change and should be mentioned in the release notes.
=> Rename AWS S3 Terraform outputs

ci/dockerfiles/deployment/Dockerfile
Using "cli.run.pivotal.io/stable?release=linux64-binary&source=github" as the source lead to errors like "chmod: cannot access 'cf': Permission denied".
ref: https://bosh.ci.cloudfoundry.org/teams/main/pipelines/bosh-bootloader/jobs/bump-bbl-deployment-image/builds/29
=> Change cf installation to use github source

application/configuration.go, bbl/main.go, commands/usage.go, commands/usage_test.go, config/global_flags.go, terraform/cli.go, terraform/executor.go
With the current settings, when we run the `bbl up` command, it calls `terraform apply -auto-approve`. In some cases, knowing that we're working with other people, some applied changes may not be something we want to apply in our infrastructure. So we'd like to be able to approve changes ourselves instead of having them applied automatically.
The apply and destroy terraform commands are always used with the `-auto-approve` option. Before using this option, it is recommended that you make sure that nobody else can modify the infrastructure outside the Terraform workflow.
This feature adds the ability to disable automatic approval when using terraform by adding the `--disable-tf-auto-approve` option and the `BBL_DISABLE_TF_AUTO_APPROVE` environment variable.
=> add the ability to disable the '-auto-approve' option with terraform

plan-patches/bosh-lite-aws/cloud-config/cloud-confg.yml, plan-patches/bosh-lite-gcp/cloud-config/bosh-lite.yml
Adds a medium VM type to the Cloud Configs of the bosh-lite-gcp and bosh-lite-aws plan patches. This is a trivial change because VM types don't matter in BOSH Lite. However, CF-D now requires a medium VM type, so this change will smooth deployment.
=> fix(plan-patches): Add medium VM type to BOSH Lite Cloud Configs

ci/dockerfiles/deployment/Dockerfile, ci/tasks/acceptance/task.yml, ci/tasks/build-release/task.yml, ci/tasks/bump-brew-tap/task.yml, ci/tasks/create-bosh-deployment-source-file/task.yml, ci/tasks/generate-version-from-sha/task.yml, ci/tasks/get-concourse-test-vars/task.yml, ci/tasks/setup-github-release/task.yml, ci/tasks/test-bosh-bootloader/task, ci/tasks/test-bosh-bootloader/task.yml
Updates Go to the latest available Docker base image.
Replaces the cryogenics image with the `cloudfoundry` image, which is actually built from the Dockerfile.
Thanks @ramonskie for the support.
=> ci: Update test environment to Go latest

ci/dockerfiles/deployment/Dockerfile
The S3 bucket from where the releases were pulled before doesn't seem to exist anymore.
The download is done similar to the `bbl` cli download a few lines further down.
Files look good now in /usr/local/bin:
```shell
root@5cd469cdd204:/usr/local/bin# ls -la
total 303428
drwxr-xr-x. 1 root root        38 Apr 16 13:35 .
drwxr-xr-x. 1 root root        16 Apr 16 13:35 ..
lrwxrwxrwx. 1 root root        37 Apr 16 13:35 aws -> /usr/local/aws-cli/v2/current/bin/aws
lrwxrwxrwx. 1 root root        47 Apr 16 13:35 aws_completer -> /usr/local/aws-cli/v2/current/bin/aws_completer
-rwxr-xr-x. 1 root root 124094215 Apr  7 18:46 bbl
-rwxr-xr-x. 1 root root  65302805 Mar 11 02:10 bosh
lrwxrwxrwx. 1 1001  118         3 Apr 11 17:22 cf -> cf8
-rwxr-xr-x. 1 1001  118  26497176 Apr 11 17:22 cf8
-rwxr-xr-x. 1 …
```
=> ci: pull bosh cli form GitHub releases
