.gitmodules

- other packages required for testing are vendored, these were missing

Vendor ginkgo & gomega

---

boshinit/manifests/fixtures/manifest.yml
boshinit/manifests/release_manifest_builder.go
boshinit/manifests/release_manifest_builder_test.go

- update bosh release to 256
- update bosh-aws-cpi release to 51

Bumps bosh-init release dependencies

---

concourse.md

was previously `lbs` and should be `lb`

correct name of lb vm_extension

---

commands/commands_usage.go
commands/commands_usage_test.go
commands/up.go
commands/up_test.go

https://github.com/cloudfoundry/bosh-bootloader/issues/80
[#135567547](https://www.pivotaltracker.com/n/projects/1488988/stories/135567547)

Add `--name` flag to up command

---

docs/getting-started-aws.md

Reverts cloudfoundry/bosh-bootloader#174

Revert "Promote `bbl print-env` workflow for AWS users"

---

acceptance-tests/azure/up_test.go
bbl/main.go
commands/azure_up.go
commands/azure_up_test.go
terraform/azure/azure_templates.go
terraform/azure/input_generator.go
terraform/azure/template_generator.go
terraform/input_generator.go
terraform/input_generator_test.go
terraform/manager.go
terraform/template_generator.go
terraform/template_generator_test.go

https://www.pivotaltracker.com/n/projects/1488988/stories/150183323

Create azure resource group

---

.gitignore
acceptance-tests/actors/bbl.go
acceptance-tests/azure/bosh_deployment_vars_test.go
bbl/main.go
bosh/manager.go
terraform/azure/azure_templates.go
terraform/azure/fixtures/azure_template_rg.tf
terraform/azure/input_generator.go
terraform/azure/input_generator_test.go
terraform/azure/output_generator.go
terraform/azure/output_generator_test.go
terraform/azure/template_generator.go
terraform/manager.go

bbl up --no-director works on azure
https://www.pivotaltracker.com/n/projects/1488988/stories/149978455

Create Azure environment for bosh

---

README.md
bosh/executor.go
bosh/executor_test.go
bosh/manager.go
bosh/manager_test.go
docs/getting-started-aws.md
terraform/aws/aws_templates.go
terraform/aws/fixtures/template_cf_lb.tf
terraform/aws/fixtures/template_cf_lb_with_domain.tf
terraform/aws/fixtures/template_concourse_lb.tf
terraform/aws/fixtures/template_no_lb.tf

[#150348596]
Signed-off-by: Rowan Jacobs <rojacobs@pivotal.io>

Enable encryption and use KMS to manage key rotation on AWS.

---

docs/concourse-aws.md

added how to upload the postgres bosh release

Update of missing info

---

docs/advanced.md

I reread the sentence permanently and wonder if my suggestion is what was meant?

simplified phrase

---

cloudconfig/azure/base_ops_template.go
cloudconfig/azure/fixtures/azure-ops.yml

Change Standard_F3 to Standard_F4 as there is no longer a
Standard_F3 instance type.
Fixes #241

Fix Azure cloud config

---

README.md

Adding additional dependencies

Adding dependencies for bosh create-env

---

terraform/aws/templates/iam.tf

Reference from [AWS CPI](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/docs/iam-policy.json)

Add missing permissions to iam role policy

---

docs/concourse.md

We found a couple small mistakes/omissions in the concourse getting-started guide. This PR addresses those.
Thanks,
Jen and @ablease

Small fixes to concourse getting started guide

---

README.md

Adjust filename for CF deployment

---

plan-patches/cfcr-aws/README.md

fix k8s api address & update stemcell for latest kubo-deployment

fix k8s api address & update stemcell

---

docs/concourse.md

Corrected so external_url is populated properly

The external url is not being populated properly

---

terraform/executor.go
terraform/executor_test.go

Run terraform init with plugin upgrade.

---

plan-patches/bosh-lite-aws/README.md
plan-patches/bosh-lite-aws/cloud-config/cloud-confg.yml
plan-patches/bosh-lite-aws/create-director-override.sh
plan-patches/bosh-lite-aws/delete-director-override.sh
plan-patches/bosh-lite-aws/terraform/bosh-lite_override.tf

Hi folks, 
Persi team needs to run a bosh-lite on aws to for CI of our EFS Volume Services.
Better for us if this plan patch is in the repo plus we thought this may be useful for others too.
Persi

bosh-lite-aws plan patch

---

plan-patches/cfcr-vsphere/README.md
plan-patches/cfcr-vsphere/cfcr-ops.yml
plan-patches/cfcr-vsphere/cloud-config/cfcr-overrides.yml
plan-patches/cfcr-vsphere/terraform/outputs-override.tf

1. Format everything better
2. We use xenial stemcell
3. Add master IP to the certificate using CFCR ops-file
4. Add `disk.enableUUID` so Persistent volumes can be used in vSphere

Improve vSphere CFCR documentation

---

plan-patches/cfcr-vsphere/README.md

plan-patch cfcr-vsphere - fixes url for vsphere xenial stemcell

---

plan-patches/cfcr-gcp/terraform/cfcr_dns_override.tf

Signed-off-by: Oleksandr Slynko <oslynko@pivotal.io>

Allow user to specify dns managed zone

---

plan-patches/cf-azure/delete-director-override.sh
plan-patches/cf-azure/delete-jumpbox-override.sh
plan-patches/cf-lite-azure/delete-director-override.sh
plan-patches/cf-lite-azure/delete-jumpbox-override.sh
plan-patches/cfcr-azure/delete-director-override.sh
plan-patches/cfcr-azure/delete-jumpbox-override.sh

or the bbl destroy would fail.

should use managed disk ops file when destroying bbl if create bbl is using it.

---

plan-patches/cfcr-azure/README.md

The release for Azure support has been cut.
The new stemcell has been cut as well

Use latest release & stemcell for Azure

---

README.md

As to help newcomers debugging their bbl error messages.

Add troubleshooting documentation

---

plan-patches/iso-segs-gcp/cloud-config/routing-iso-segs.yml
plan-patches/iso-segs-gcp/terraform/routing-iso-segs.tf

[#170704201]
Co-authored-by: Danny Berger <dberger@pivotal.io>

Fix iso-seg routers to use TCP LB

---

docs/concourse.md

The Bionic update is kind of obvious. The AZs is from #500.

Fix concourse quick start w/ Bionic and AZs

---

plan-patches/gcs-blobstore-gcp/README.md
plan-patches/gcs-blobstore-gcp/terraform/gcs_blobstore_buckets_override.tf
plan-patches/gcs-blobstore-gcp/terraform/gcs_blobstore_iam_override.tf
plan-patches/gcs-blobstore-gcp/terraform/gcs_blobstore_outputs_override.tf

New PR based on #435, which was auto-closed when the master branch was renamed to main.

Add plan-patch for GCS blobstore resources

---

cloudconfig/aws/base_ops_template.go
cloudconfig/aws/fixtures/aws-ops.yml
cloudconfig/azure/base_ops_template.go
cloudconfig/azure/fixtures/azure-ops.yml
cloudconfig/gcp/base_ops_template.go
cloudconfig/gcp/fixtures/gcp-ops.yml

To realize this RFC:
https://github.com/cloudfoundry/community/pull/290
Signed-off-by: David Stevenson <stevensonda@vmware.com>

Switch cloudconfig to modern and smaller VM sizes

---

cloudconfig/azure/base_ops_template.go

Fix vm_type of compilation vm for Azure.

fix vm_type of compilation vm for Azure

---

plan-patches/bosh-lite-gcp/terraform/bosh-lite.tf

Fix: bosh-lite-gcp plan patch

---

cloudconfig/aws/base_ops_template.go
cloudconfig/aws/fixtures/aws-ops.yml
cloudconfig/azure/base_ops_template.go
cloudconfig/azure/fixtures/azure-ops.yml
cloudconfig/gcp/base_ops_template.go
cloudconfig/gcp/fixtures/gcp-ops.yml
cloudconfig/openstack/base_ops_template.go

This is a PR to scale up compilation VMs to fix pxc-release issue: https://github.com/cloudfoundry/pxc-release/issues/53

Scale up compilation VMs to fix pxc-release issue.

---

ci/dockerfiles/deployment/Dockerfile

de docker image should always download the latest jq version

get the latest jq version

---

terraform/aws/templates/base.tf
terraform/aws/templates/concourse_lb.tf

resolve deprecation warning in aws_eip resource
resolve concourse-lb issue with aws_lb subnets property using flatten syntax consistent with cf load balancer

issue-627-aws-eip-and-lb-changes

---

ci/pipelines/bosh-bootloader.yml

this will save us 10%
Related to https://github.com/cloudfoundry/community/issues/1184
and https://github.com/cloudfoundry/bosh-stemcells-ci/pull/33

witch to cheaper region
